# Language: Bahasa Indonesia
# Program iseng untuk menghitung rerata skor UTBK (2023)
# Untuk digunakan secara pribadi :)

print("Menghitung rerata skor UTBK, SNBT 2023")
print("---------------------------------------")
print(".")
pu = float(input("Kemampuan penalaran umum: "))
pk = float(input("Kemampuan kuantitatif: "))
ppu = float(input("Pengetahuan dan pemahaman umum: "))
pbm = float(input("Kemampuan memahami bacaan dan menulis: "))
print(".")
litbah = float(input("Literasi Bahasa Indonesia: "))
liteng = float(input("Literasi Bahasa Inggris: "))
print(".")
pm = float(input("Penalaran Matematika: "))
print(".")
print("---------------------------------------")
average = round(((pu+pk+ppu+pbm+litbah+liteng+pm)/7), 2)
print(f"Rerata skor UTBK anda adalah {average}")
