print("Welcome to Mad Libs Story Generator! Please insert the given information below.")
nationality = input("Please enter a nationality here: ")
print("---------------------------------------------------")
adj1 = input("Please enter an adjective here: ")
print("---------------------------------------------------")
noun1 = input("Please enter a noun here:")
print("---------------------------------------------------")
adj2 = input("Please enter another adjective here: ")
print("---------------------------------------------------")
noun2 = input("Please enter another noun here:")
print("---------------------------------------------------")
noun3 = input("Please enter another noun here:")
print("---------------------------------------------------")
print("Please enter a time, past. (e.g. = one year ago, one month ago.)")
time = input("here:")
print("---------------------------------------------------")
verb1 = input("Please enter a verb here:")
print("---------------------------------------------------")
verb2 = input("Please enter another verb here")
print("---------------------------------------------------")
print(f"There is an Infamous Hero from {nationality}, he has such a {adj1} {noun1} and some {adj2} {noun2}.")
print(f"He saves people from {noun3} that occured {time}. Usually, he likes to {verb1} and {verb2} alot.")